import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Phase 5: CNN Classifier Training (ResNet-50 vs EfficientNet-B0)\n",
    "\n",
    "This notebook trains and evaluates two CNN architectures to classify SEM defect crops into 3 classes:\n",
    "0: Inclusion-Particle, 1: Porosity, 2: Tear-Delamination.\n",
    "\n",
    "It is designed to run on a Google Colab GPU and persist all checkpoints and metrics to Google Drive."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Setup & Environment Audit\n",
    "!pip install torch torchvision pandas matplotlib seaborn scikit-learn > /dev/null 2>&1\n",
    "import os\n",
    "import random\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torchvision import datasets, transforms, models\n",
    "from torch.utils.data import DataLoader, WeightedRandomSampler\n",
    "from sklearn.metrics import classification_report, confusion_matrix\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from PIL import Image\n",
    "import json\n",
    "import time\n",
    "\n",
    "# Set seeds for reproducibility\n",
    "def set_seed(seed=42):\n",
    "    random.seed(seed)\n",
    "    np.random.seed(seed)\n",
    "    torch.manual_seed(seed)\n",
    "    torch.cuda.manual_seed_all(seed)\n",
    "    torch.backends.cudnn.deterministic = True\n",
    "    torch.backends.cudnn.benchmark = False\n",
    "set_seed(42)\n",
    "\n",
    "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "print(f\"Using device: {device}\")\n",
    "if device.type == 'cuda':\n",
    "    print(f\"GPU: {torch.cuda.get_device_name(0)}\")\n",
    "    print(f\"VRAM: {round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2)} GB\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 2. Mount Google Drive & Locate / Extract Classifier Dataset\n",
    "import zipfile\n",
    "import shutil\n",
    "\n",
    "if os.path.exists('/content/drive/MyDrive'):\n",
    "    print(\"✅ Google Drive is already mounted.\")\n",
    "else:\n",
    "    try:\n",
    "        from google.colab import drive\n",
    "        drive.mount('/content/drive')\n",
    "        print(\"✅ Google Drive successfully mounted.\")\n",
    "    except Exception as e:\n",
    "        print(\"⚠️ Remote Colab UI auth blocked. Please mount Drive manually using the Colab left sidebar -> Files -> Mount Drive.\")\n",
    "\n",
    "PROJECT_ROOT = '/content/drive/MyDrive/sem_defect_project'\n",
    "RUNS_DIR = f\"{PROJECT_ROOT}/runs/classify\"\n",
    "os.makedirs(RUNS_DIR, exist_ok=True)\n",
    "\n",
    "# Smart Dataset Detection:\n",
    "# Fast local path in Colab for superior PyTorch DataLoader throughput:\n",
    "LOCAL_DATASET = '/content/classifier_crops'\n",
    "\n",
    "possible_zips = [\n",
    "    '/content/classifier_crops.zip',\n",
    "    f\"{PROJECT_ROOT}/classifier_crops.zip\",\n",
    "    f\"{PROJECT_ROOT}/datasets/classifier_crops.zip\",\n",
    "    '/content/drive/MyDrive/classifier_crops.zip'\n",
    "]\n",
    "\n",
    "possible_folders = [\n",
    "    LOCAL_DATASET,\n",
    "    f\"{PROJECT_ROOT}/datasets/classifier_crops\",\n",
    "    f\"{PROJECT_ROOT}/classifier_crops\"\n",
    "]\n",
    "\n",
    "DATASET_ROOT = None\n",
    "\n",
    "# 1. Check if already extracted locally\n",
    "if os.path.exists(os.path.join(LOCAL_DATASET, 'train')):\n",
    "    DATASET_ROOT = LOCAL_DATASET\n",
    "    print(f\"✅ Found local fast dataset at: {DATASET_ROOT}\")\n",
    "else:\n",
    "    # 2. Check for zip file to extract locally (10x faster training than Drive FUSE mount)\n",
    "    zip_found = None\n",
    "    for zp in possible_zips:\n",
    "        if os.path.exists(zp):\n",
    "            zip_found = zp\n",
    "            break\n",
    "    \n",
    "    if zip_found:\n",
    "        print(f\"📦 Extracting {zip_found} to /content/ for fast GPU training...\")\n",
    "        with zipfile.ZipFile(zip_found, 'r') as zip_ref:\n",
    "            zip_ref.extractall('/content')\n",
    "        if os.path.exists(os.path.join(LOCAL_DATASET, 'train')):\n",
    "            DATASET_ROOT = LOCAL_DATASET\n",
    "        elif os.path.exists('/content/train'):\n",
    "            DATASET_ROOT = '/content'\n",
    "        print(f\"✅ Extracted! Active dataset at: {DATASET_ROOT}\")\n",
    "    else:\n",
    "        # 3. Check for existing folders in Drive\n",
    "        for fp in possible_folders:\n",
    "            if os.path.exists(os.path.join(fp, 'train')):\n",
    "                print(f\"📁 Found dataset folder at {fp}. Copying to local fast SSD {LOCAL_DATASET}...\")\n",
    "                shutil.copytree(fp, LOCAL_DATASET, dirs_exist_ok=True)\n",
    "                DATASET_ROOT = LOCAL_DATASET\n",
    "                print(f\"✅ Ready! Active dataset at: {DATASET_ROOT}\")\n",
    "                break\n",
    "\n",
    "if DATASET_ROOT is None:\n",
    "    raise FileNotFoundError(\n",
    "        f\"❌ Classifier dataset not found!\\n\\n\"\n",
    "        f\"Please upload 'classifier_crops.zip' (27 MB) using either:\\n\"\n",
    "        f\"  1. Upload to Google Drive at: {PROJECT_ROOT}/classifier_crops.zip\\n\"\n",
    "        f\"  2. Or drag & drop directly into Colab's left sidebar 'Files' tab (/content/classifier_crops.zip)\\n\"\n",
    "    )\n",
    "\n",
    "print(f\"🎯 Active Dataset Directory: {DATASET_ROOT}\")\n",
    "print(f\"📁 Runs Directory: {RUNS_DIR}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3. Dataset Verification & Sanity Checks\n",
    "splits = ['train', 'valid', 'test']\n",
    "class_counts = {}\n",
    "\n",
    "print(\"--- DATASET SANITY CHECK ---\")\n",
    "for split in splits:\n",
    "    split_dir = os.path.join(DATASET_ROOT, split)\n",
    "    if not os.path.exists(split_dir):\n",
    "        raise FileNotFoundError(f\"{split_dir} not found!\")\n",
    "    \n",
    "    print(f\"\\nSplit: {split}\")\n",
    "    split_total = 0\n",
    "    for cls_name in sorted(os.listdir(split_dir)):\n",
    "        cls_dir = os.path.join(split_dir, cls_name)\n",
    "        if os.path.isdir(cls_dir):\n",
    "            count = len(os.listdir(cls_dir))\n",
    "            split_total += count\n",
    "            if split == 'train':\n",
    "                class_counts[cls_name] = count\n",
    "            print(f\"  {cls_name}: {count} images\")\n",
    "    print(f\"  TOTAL {split}: {split_total}\")\n",
    "\n",
    "if 'train' in splits:\n",
    "    total_train = sum(class_counts.values())\n",
    "    weights = [total_train / class_counts[c] for c in class_counts.keys()]\n",
    "    # Normalize weights so the minimum weight is 1.0\n",
    "    min_w = min(weights)\n",
    "    class_weights = torch.FloatTensor([w / min_w for w in weights]).to(device)\n",
    "    \n",
    "    print(f\"\\nCalculated Class Weights for CrossEntropyLoss:\")\n",
    "    for cls_name, w in zip(class_counts.keys(), class_weights):\n",
    "        print(f\"  {cls_name}: {w.item():.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4. Data Augmentation Policy\n",
    "\"\"\"\n",
    "AUGMENTATION JUSTIFICATION:\n",
    "SEM topography does not have a strict gravity/up-down orientation like natural images.\n",
    "Therefore, H-Flips, V-Flips, and slight rotations are physically valid and preserve defect morphology.\n",
    "We avoid heavy color jitter or blurring to preserve the structural contrast that differentiates porosity from tears.\n",
    "\"\"\"\n",
    "IMG_SIZE = 224\n",
    "BATCH_SIZE = 32\n",
    "\n",
    "train_transform = transforms.Compose([\n",
    "    transforms.Resize((IMG_SIZE, IMG_SIZE)),\n",
    "    transforms.RandomHorizontalFlip(p=0.5),\n",
    "    transforms.RandomVerticalFlip(p=0.5),\n",
    "    transforms.RandomRotation(degrees=15),\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
    "])\n",
    "\n",
    "val_test_transform = transforms.Compose([\n",
    "    transforms.Resize((IMG_SIZE, IMG_SIZE)),\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
    "])\n",
    "\n",
    "train_dataset = datasets.ImageFolder(os.path.join(DATASET_ROOT, 'train'), transform=train_transform)\n",
    "valid_dataset = datasets.ImageFolder(os.path.join(DATASET_ROOT, 'valid'), transform=val_test_transform)\n",
    "test_dataset = datasets.ImageFolder(os.path.join(DATASET_ROOT, 'test'), transform=val_test_transform)\n",
    "\n",
    "train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True)\n",
    "valid_loader = DataLoader(valid_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)\n",
    "test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)\n",
    "\n",
    "class_names = train_dataset.classes\n",
    "print(f\"Classes: {class_names}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 5. Training Engine Definition\n",
    "def train_model(model, model_name, criterion, optimizer, scheduler, num_epochs=30, patience=7):\n",
    "    exp_dir = os.path.join(RUNS_DIR, model_name)\n",
    "    os.makedirs(exp_dir, exist_ok=True)\n",
    "    \n",
    "    best_val_loss = float('inf')\n",
    "    epochs_no_improve = 0\n",
    "    history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}\n",
    "    \n",
    "    start_time = time.time()\n",
    "    for epoch in range(num_epochs):\n",
    "        model.train()\n",
    "        running_loss, running_corrects = 0.0, 0\n",
    "        \n",
    "        for inputs, labels in train_loader:\n",
    "            inputs, labels = inputs.to(device), labels.to(device)\n",
    "            optimizer.zero_grad()\n",
    "            outputs = model(inputs)\n",
    "            loss = criterion(outputs, labels)\n",
    "            _, preds = torch.max(outputs, 1)\n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "            \n",
    "            running_loss += loss.item() * inputs.size(0)\n",
    "            running_corrects += torch.sum(preds == labels.data)\n",
    "            \n",
    "        epoch_loss = running_loss / len(train_dataset)\n",
    "        epoch_acc = running_corrects.double() / len(train_dataset)\n",
    "        \n",
    "        model.eval()\n",
    "        val_loss, val_corrects = 0.0, 0\n",
    "        with torch.no_grad():\n",
    "            for inputs, labels in valid_loader:\n",
    "                inputs, labels = inputs.to(device), labels.to(device)\n",
    "                outputs = model(inputs)\n",
    "                loss = criterion(outputs, labels)\n",
    "                _, preds = torch.max(outputs, 1)\n",
    "                val_loss += loss.item() * inputs.size(0)\n",
    "                val_corrects += torch.sum(preds == labels.data)\n",
    "                \n",
    "        val_loss = val_loss / len(valid_dataset)\n",
    "        val_acc = val_corrects.double() / len(valid_dataset)\n",
    "        \n",
    "        scheduler.step(val_loss)\n",
    "        \n",
    "        history['train_loss'].append(epoch_loss)\n",
    "        history['train_acc'].append(epoch_acc.item())\n",
    "        history['val_loss'].append(val_loss)\n",
    "        history['val_acc'].append(val_acc.item())\n",
    "        \n",
    "        print(f\"Epoch {epoch+1}/{num_epochs} - Train Loss: {epoch_loss:.4f} Acc: {epoch_acc:.4f} | Val Loss: {val_loss:.4f} Acc: {val_acc:.4f}\")\n",
    "        \n",
    "        if val_loss < best_val_loss:\n",
    "            best_val_loss = val_loss\n",
    "            epochs_no_improve = 0\n",
    "            torch.save(model.state_dict(), os.path.join(exp_dir, 'best.pt'))\n",
    "        else:\n",
    "            epochs_no_improve += 1\n",
    "            if epochs_no_improve >= patience:\n",
    "                print(\"Early stopping triggered!\")\n",
    "                break\n",
    "                \n    torch.save(model.state_dict(), os.path.join(exp_dir, 'last.pt'))\n",
    "    \n",
    "    with open(os.path.join(exp_dir, 'history.json'), 'w') as f:\n",
    "        json.dump(history, f, indent=4)\n",
    "        \n",
    "    print(f\"Training complete in {(time.time() - start_time)/60:.2f} minutes.\")\n",
    "    return history"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 6. Evaluation Function Definition\n",
    "def evaluate_model(model, model_name, dataloader, dataset_name=\"test\"):\n",
    "    exp_dir = os.path.join(RUNS_DIR, model_name)\n",
    "    model.load_state_dict(torch.load(os.path.join(exp_dir, 'best.pt')))\n",
    "    model.eval()\n",
    "    \n",
    "    all_preds, all_labels = [], []\n",
    "    with torch.no_grad():\n",
    "        for inputs, labels in dataloader:\n",
    "            inputs, labels = inputs.to(device), labels.to(device)\n",
    "            outputs = model(inputs)\n",
    "            _, preds = torch.max(outputs, 1)\n",
    "            all_preds.extend(preds.cpu().numpy())\n",
    "            all_labels.extend(labels.cpu().numpy())\n",
    "            \n",
    "    print(f\"\\nClassification Report ({dataset_name}):\")\n",
    "    report = classification_report(all_labels, all_preds, target_names=class_names, digits=4)\n",
    "    print(report)\n",
    "    \n",
    "    report_dict = classification_report(all_labels, all_preds, target_names=class_names, output_dict=True)\n",
    "    with open(os.path.join(exp_dir, f'{dataset_name}_metrics.json'), 'w') as f:\n",
    "        json.dump(report_dict, f, indent=4)\n",
    "        \n",
    "    # Confusion Matrix\n",
    "    cm = confusion_matrix(all_labels, all_preds)\n",
    "    plt.figure(figsize=(8,6))\n",
    "    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)\n",
    "    plt.xlabel('Predicted')\n",
    "    plt.ylabel('True')\n",
    "    plt.title(f'Confusion Matrix: {model_name} on {dataset_name} set')\n",
    "    plt.savefig(os.path.join(exp_dir, f'{dataset_name}_confusion_matrix.png'))\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "### **PHASE 5 APPROVED: MODEL TRAINING & COMPARISON**\n",
    "Executing training for ResNet-50 and EfficientNet-B0 according to the approved Phase 5 plan.\n",
    "---"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 7. ResNet-50 Training (EXP-03-ResNet50)\n",
    "print(\"\\n--- Initializing ResNet-50 ---\")\n",
    "resnet = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)\n",
    "\n",
    "# Freeze all layers except the last block\n",
    "for param in resnet.parameters():\n",
    "    param.requires_grad = False\n",
    "for param in resnet.layer4.parameters():\n",
    "    param.requires_grad = True\n",
    "\n",
    "num_ftrs = resnet.fc.in_features\n",
    "resnet.fc = nn.Sequential(\n",
    "    nn.Dropout(0.5),\n",
    "    nn.Linear(num_ftrs, 3)\n",
    ")\n",
    "resnet = resnet.to(device)\n",
    "\n",
    "# Using Weighted CrossEntropyLoss\n",
    "criterion = nn.CrossEntropyLoss(weight=class_weights)\n",
    "optimizer = optim.AdamW(filter(lambda p: p.requires_grad, resnet.parameters()), lr=1e-4, weight_decay=1e-3)\n",
    "scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3)\n",
    "\n",
    "print(\"Starting ResNet-50 Training...\")\n",
    "history_resnet = train_model(resnet, \"EXP-03-ResNet50\", criterion, optimizer, scheduler, num_epochs=40, patience=7)\n",
    "\n",
    "print(\"\\n--- Evaluating ResNet-50 ---\")\n",
    "evaluate_model(resnet, \"EXP-03-ResNet50\", valid_loader, \"valid\")\n",
    "evaluate_model(resnet, \"EXP-03-ResNet50\", test_loader, \"test\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 8. EfficientNet-B0 Training (EXP-04-EfficientNetB0)\n",
    "print(\"\\n--- Initializing EfficientNet-B0 ---\")\n",
    "effnet = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.IMAGENET1K_V1)\n",
    "\n",
    "# Freeze all layers except the last few blocks\n",
    "for param in effnet.parameters():\n",
    "    param.requires_grad = False\n",
    "for param in effnet.features[7:].parameters():\n",
    "    param.requires_grad = True\n",
    "\n",
    "num_ftrs = effnet.classifier[1].in_features\n",
    "effnet.classifier = nn.Sequential(\n",
    "    nn.Dropout(0.5),\n",
    "    nn.Linear(num_ftrs, 3)\n",
    ")\n",
    "effnet = effnet.to(device)\n",
    "\n",
    "criterion = nn.CrossEntropyLoss(weight=class_weights)\n",
    "optimizer = optim.AdamW(filter(lambda p: p.requires_grad, effnet.parameters()), lr=1e-4, weight_decay=1e-3)\n",
    "scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3)\n",
    "\n",
    "print(\"Starting EfficientNet-B0 Training...\")\n",
    "history_effnet = train_model(effnet, \"EXP-04-EfficientNetB0\", criterion, optimizer, scheduler, num_epochs=40, patience=7)\n",
    "\n",
    "print(\"\\n--- Evaluating EfficientNet-B0 ---\")\n",
    "evaluate_model(effnet, \"EXP-04-EfficientNetB0\", valid_loader, \"valid\")\n",
    "evaluate_model(effnet, \"EXP-04-EfficientNetB0\", test_loader, \"test\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

out_path = r"c:\Users\syed mohammad anas\Desktop\sir_khurram_project\sem_defect_project\notebooks\04_classifier_training.ipynb"
with open(out_path, 'w') as f:
    json.dump(notebook, f, indent=1)
print(f"Created notebook at {out_path}")
